In [2]:
import pickle

In [3]:
with open('all_data.pickle', 'rb') as f:
    load_data = pickle.load(f)

In [4]:
load_data

,CO,DO,Humid,LPG,MQ137,SMOKE,Temperature,data_type,datetime,day,month,place_name,sensor_id,year
71,NaN,10.4,NaN,NaN,NaN,NaN,NaN,DO,2019-09-12_12:38:09,12.0,9.0,aquarium_4,None,2019.0
74,NaN,NaN,NaN,NaN,NaN,NaN,12.845000,water_temp,2019-09-14_07:30:18_3,14.0,9.0,aquarium_5,28-030897941c59,2019.0
76,NaN,9.46,NaN,NaN,NaN,NaN,NaN,DO,2019-09-10_13:55:14,10.0,9.0,aquarium_1,None,2019.0
114,NaN,10.5,NaN,NaN,NaN,NaN,NaN,DO,2019-09-12_15:15:29,12.0,9.0,aquarium_5,None,2019.0
151,NaN,10.2,NaN,NaN,NaN,NaN,NaN,DO,2019-09-13_03:30:17_1,13.0,9.0,aquarium_1,None,2019.0
217,NaN,9.36,NaN,NaN,NaN,NaN,13.570000,DO,2019-09-10_11:23:01,10.0,9.0,aquarium_1,None,2019.0
221,NaN,9.62,NaN,NaN,NaN,NaN,NaN,DO,2019-09-15_01:00:23_1,15.0,9.0,aquarium_1,None,2019.0
266,NaN,NaN,NaN,NaN,NaN,NaN,12.845000,water_temp,2019-09-14_20:30:14_3,14.0,9.0,aquarium_5,28-030897941c59,2019.0
277,NaN,10.6,NaN,NaN,NaN,NaN,NaN,DO,2019-09-14_12:30:20_3,14.0,9.0,aquarium_5,None,2019.0
295,NaN,9.55,NaN,NaN,NaN,NaN,NaN,DO,2019-09-12_20:30:23_1,12.0,9.0,aquarium_1,None,2019.0
327,NaN,NaN,NaN,NaN,NaN,NaN,13.320000,water_temp,2019-09-10_11:29:59,10.0,9.0,aquarium_1,28-030997945f64,2019.0
344,NaN,10.4,NaN,NaN,NaN,NaN,NaN,DO,2019-09-13_23:00:18_3,13.0,9.0,aquarium_5,None,2019.0
472,NaN,NaN,78.099998,NaN,NaN,NaN,19.900000,temp-humid,2019-09-13_20:30:25_3,13.0,9.0,aquarium_5,NaN,2019.0
499,NaN,9.63,NaN,NaN,NaN,NaN,NaN,DO,2019-09-12_16:30:10_1,12.0,9.0,aquarium_1,None,2019.0
521,NaN,NaN,NaN,NaN,NaN,NaN,13.257000,water_temp,2019-09-10_13:05:16,10.0,9.0,aquarium_1,28-030997945f64,2019.0
528,NaN,NaN,82.300003,NaN,NaN,NaN,19.700001,temp-humid,2019-09-13_09:00:16_3,13.0,9.0,aquarium_5,NaN,2019.0
563,NaN,9.47,NaN,NaN,NaN,NaN,NaN,DO,2019-09-12_19:30:14_1,12.0,9.0,aquarium_1,None,2019.0
574,NaN,NaN,77.300003,NaN,NaN,NaN,20.900000,temp-humid,2019-09-12_21:00:01_3,12.0,9.0,aquarium_5,NaN,2019.0
576,NaN,8.72,NaN,NaN,NaN,NaN,NaN,DO,2019-09-14_00:30:16_1,14.0,9.0,aquarium_1,None,2019.0
615,NaN,NaN,NaN,NaN,0.0044971,NaN,NaN,GAS_MQ137,2019-09-12_22:02:58_1,12.0,9.0,aquarium_1,None,2019.0
657,NaN,NaN,NaN,NaN,NaN,NaN,12.507000,water_temp,2019-09-12_23:30:07_1,12.0,9.0,aquarium_1,28-030997945f64,2019.0
679,NaN,10.4,NaN,NaN,NaN,NaN,NaN,DO,2019-09-14_07:30:32_3,14.0,9.0,aquarium_5,None,2019.0
733,NaN,NaN,NaN,NaN,NaN,NaN,12.907000,water_temp,2019-09-15_05:30:15_3,15.0,9.0,aquarium_5,28-030897941c59,2019.0
788,NaN,NaN,79.500000,NaN,NaN,NaN,20.200001,temp-humid,2019-09-13_00:00:04_3,13.0,9.0,aquarium_5,NaN,2019.0
803,NaN,NaN,NaN,NaN,NaN,NaN,12.720000,water_temp,2019-09-14_20:00:17_3,14.0,9.0,aquarium_5,28-030897941c59,2019.0
823,NaN,10.5,NaN,NaN,NaN,NaN,NaN,DO,2019-09-12_14:15:30,12.0,9.0,aquarium_5,None,2019.0
887,NaN,NaN,NaN,NaN,NaN,NaN,12.657000,water_temp,2019-09-13_21:00:05_3,13.0,9.0,aquarium_5,28-030897941c59,2019.0
953,NaN,NaN,NaN,NaN,NaN,NaN,13.070000,water_temp,2019-09-10_14:25:11,10.0,9.0,aquarium_1,28-030997945f64,2019.0
959,NaN,9.59,NaN,NaN,NaN,NaN,NaN,DO,2019-09-13_07:00:37_1,13.0,9.0,aquarium_1,None,2019.0
1009,NaN,NaN,NaN,NaN,NaN,NaN,12.570000,water_temp,2019-09-13_09:00:09_1,13.0,9.0,aquarium_1,28-030997945f64,2019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73448,NaN,NaN,NaN,NaN,NaN,NaN,12.845000,water_temp,2019-09-13_12:00:06_3,13.0,9.0,aquarium_5,28-030897941c59,2019.0
73463,NaN,NaN,NaN,NaN,64625.4,NaN,NaN,GAS_MQ137,2019-09-10_14:17:28,10.0,9.0,aquarium_1,None,2019.0
73498,NaN,8.82,NaN,NaN,NaN,NaN,NaN,DO,2019-09-14_00:00:24_1,14.0,9.0,aquarium_1,None,2019.0
73508,NaN,NaN,NaN,NaN,NaN,NaN,13.445000,water_temp,2019-09-10_12:40:10,10.0,9.0,aquarium_1,28-030997945f64,2019.0
73638,NaN,10.6,NaN,NaN,NaN,NaN,NaN,DO,2019-09-14_16:30:30_3,14.0,9.0,aquarium_5,None,2019.0
73681,NaN,NaN,NaN,NaN,NaN,NaN,13.195000,water_temp,2019-09-10_14:46:42,10.0,9.0,aquarium_1,28-030997945f64,2019.0
73709,NaN,10.6,NaN,NaN,NaN,NaN,NaN,DO,2019-09-15_08:30:19_3,15.0,9.0,aquarium_5,None,2019.0
73723,NaN,NaN,NaN,NaN,NaN,NaN,12.445000,water_temp,2019-09-13_22:00:03_1,13.0,9.0,aquarium_1,28-030997945f64,2019.0
73731,NaN,NaN,NaN,NaN,NaN,NaN,13.445000,water_temp,2019-09-10_12:15:19,10.0,9.0,aquarium_1,28-030997945f64,2019.0
73787,NaN,NaN,NaN,NaN,NaN,NaN,12.820000,water_temp,2019-09-12_10:56:37,12.0,9.0,aquarium_1,28-030997945f64,2019.0
73803,NaN,NaN,NaN,NaN,NaN,NaN,12.657000,water_temp,2019-09-15_04:30:24_3,15.0,9.0,aquarium_5,28-030897941c59,2019.0
73806,NaN,8.78,NaN,NaN,NaN,NaN,NaN,DO,2019-09-14_00:00:31_1,14.0,9.0,aquarium_1,None,2019.0
73813,NaN,NaN,NaN,NaN,NaN,NaN,14.220000,water_temp,2019-09-12_21:00:02_3,12.0,9.0,aquarium_5,28-030897941c59,2019.0
73937,NaN,7.92,NaN,NaN,NaN,NaN,NaN,DO,2019-09-14_03:30:27_3,14.0,9.0,aquarium_5,None,2019.0
73961,NaN,10.7,NaN,NaN,NaN,NaN,NaN,DO,2019-09-14_15:00:08_3,14.0,9.0,aquarium_5,None,2019.0
73982,NaN,NaN,NaN,NaN,NaN,NaN,12.907000,water_temp,2019-09-13_07:30:01_3,13.0,9.0,aquarium_5,28-030897941c59,2019.0
74077,NaN,NaN,76.099998,NaN,NaN,NaN,21.400000,temp-humid,2019-09-12_19:00:21_3,12.0,9.0,aquarium_5,NaN,2019.0
74280,NaN,8.92,NaN,NaN,NaN,NaN,NaN,DO,2019-09-10_12:30:06,10.0,9.0,aquarium_1,None,2019.0
74294,NaN,NaN,NaN,NaN,0.0231066,NaN,NaN,GAS_MQ137,2019-09-13_00:32:57_1,13.0,9.0,aquarium_1,None,2019.0
74300,NaN,NaN,80.800003,NaN,NaN,NaN,20.400000,temp-humid,2019-09-13_14:30:13_3,13.0,9.0,aquarium_5,NaN,2019.0
74312,NaN,NaN,77.199997,NaN,NaN,NaN,23.799999,temp-humid,2019-09-12_14:45:20,12.0,9.0,aquarium_5,NaN,2019.0
74484,NaN,NaN,NaN,NaN,NaN,NaN,13.157000,water_temp,2019-09-13_08:30:18_3,13.0,9.0,aquarium_5,28-030897941c59,2019.0
74497,NaN,NaN,NaN,NaN,NaN,NaN,14.095000,water_temp,2019-09-12_21:00:13_3,12.0,9.0,aquarium_5,28-030897941c59,2019.0
74590,NaN,NaN,NaN,NaN,NaN,NaN,13.032000,water_temp,2019-09-14_22:30:10_3,14.0,9.0,aquarium_5,28-030897941c59,2019.0
74593,NaN,NaN,78.500000,NaN,NaN,NaN,23.700001,temp-humid,2019-09-12_13:45:18,12.0,9.0,aquarium_5,NaN,2019.0
74612,NaN,NaN,NaN,NaN,NaN,NaN,12.657000,water_temp,2019-09-14_15:00:22_3,14.0,9.0,aquarium_5,28-030897941c59,2019.0
74626,NaN,NaN,NaN,NaN,NaN,NaN,12.320000,water_temp,2019-09-13_00:00:29_1,13.0,9.0,aquarium_1,28-030997945f64,2019.0
74639,NaN,NaN,NaN,NaN,NaN,NaN,12.882000,water_temp,2019-09-15_03:00:03_1,15.0,9.0,aquarium_1,28-030997945f64,2019.0
74641,NaN,NaN,NaN,NaN,NaN,NaN,12.695000,water_temp,2019-09-15_12:30:11_1,15.0,9.0,aquarium_1,28-030997945f64,2019.0
74686,NaN,NaN,78.599998,NaN,NaN,NaN,20.100000,temp-humid,2019-09-13_19:30:03_3,13.0,9.0,aquarium_5,NaN,2019.0

In [5]:
print(load_data)

        CO    DO      Humid  LPG      MQ137 SMOKE  Temperature   data_type  \
71     NaN  10.4        NaN  NaN        NaN   NaN          NaN          DO
74     NaN   NaN        NaN  NaN        NaN   NaN    12.845000  water_temp
76     NaN  9.46        NaN  NaN        NaN   NaN          NaN          DO
114    NaN  10.5        NaN  NaN        NaN   NaN          NaN          DO
151    NaN  10.2        NaN  NaN        NaN   NaN          NaN          DO
217    NaN  9.36        NaN  NaN        NaN   NaN    13.570000          DO
221    NaN  9.62        NaN  NaN        NaN   NaN          NaN          DO
266    NaN   NaN        NaN  NaN        NaN   NaN    12.845000  water_temp
277    NaN  10.6        NaN  NaN        NaN   NaN          NaN          DO
295    NaN  9.55        NaN  NaN        NaN   NaN          NaN          DO
327    NaN   NaN        NaN  NaN        NaN   NaN    13.320000  water_temp
344    NaN  10.4        NaN  NaN        NaN   NaN          NaN          DO
472    NaN   NaN  78.099998  NaN        NaN   NaN    19.900000  temp-humid
499    NaN  9.63        NaN  NaN        NaN   NaN          NaN          DO
521    NaN   NaN        NaN  NaN        NaN   NaN    13.257000  water_temp
528    NaN   NaN  82.300003  NaN        NaN   NaN    19.700001  temp-humid
563    NaN  9.47        NaN  NaN        NaN   NaN          NaN          DO
574    NaN   NaN  77.300003  NaN        NaN   NaN    20.900000  temp-humid
576    NaN  8.72        NaN  NaN        NaN   NaN          NaN          DO
615    NaN   NaN        NaN  NaN  0.0044971   NaN          NaN   GAS_MQ137
657    NaN   NaN        NaN  NaN        NaN   NaN    12.507000  water_temp
679    NaN  10.4        NaN  NaN        NaN   NaN          NaN          DO
733    NaN   NaN        NaN  NaN        NaN   NaN    12.907000  water_temp
788    NaN   NaN  79.500000  NaN        NaN   NaN    20.200001  temp-humid
803    NaN   NaN        NaN  NaN        NaN   NaN    12.720000  water_temp
823    NaN  10.5        NaN  NaN        NaN   NaN          NaN          DO
887    NaN   NaN        NaN  NaN        NaN   NaN    12.657000  water_temp
953    NaN   NaN        NaN  NaN        NaN   NaN    13.070000  water_temp
959    NaN  9.59        NaN  NaN        NaN   NaN          NaN          DO
1009   NaN   NaN        NaN  NaN        NaN   NaN    12.570000  water_temp
...    ...   ...        ...  ...        ...   ...          ...         ...
73448  NaN   NaN        NaN  NaN        NaN   NaN    12.845000  water_temp
73463  NaN   NaN        NaN  NaN    64625.4   NaN          NaN   GAS_MQ137
73498  NaN  8.82        NaN  NaN        NaN   NaN          NaN          DO
73508  NaN   NaN        NaN  NaN        NaN   NaN    13.445000  water_temp
73638  NaN  10.6        NaN  NaN        NaN   NaN          NaN          DO
73681  NaN   NaN        NaN  NaN        NaN   NaN    13.195000  water_temp
73709  NaN  10.6        NaN  NaN        NaN   NaN          NaN          DO
73723  NaN   NaN        NaN  NaN        NaN   NaN    12.445000  water_temp
73731  NaN   NaN        NaN  NaN        NaN   NaN    13.445000  water_temp
73787  NaN   NaN        NaN  NaN        NaN   NaN    12.820000  water_temp
73803  NaN   NaN        NaN  NaN        NaN   NaN    12.657000  water_temp
73806  NaN  8.78        NaN  NaN        NaN   NaN          NaN          DO
73813  NaN   NaN        NaN  NaN        NaN   NaN    14.220000  water_temp
73937  NaN  7.92        NaN  NaN        NaN   NaN          NaN          DO
73961  NaN  10.7        NaN  NaN        NaN   NaN          NaN          DO
73982  NaN   NaN        NaN  NaN        NaN   NaN    12.907000  water_temp
74077  NaN   NaN  76.099998  NaN        NaN   NaN    21.400000  temp-humid
74280  NaN  8.92        NaN  NaN        NaN   NaN          NaN          DO
74294  NaN   NaN        NaN  NaN  0.0231066   NaN          NaN   GAS_MQ137
74300  NaN   NaN  80.800003  NaN        NaN   NaN    20.400000  temp-humid
74312  NaN   NaN  77.199997  NaN        NaN   NaN    23.799999  temp-humid
74484  NaN   NaN        NaN  NaN        NaN   NaN    13.157000  water_temp
74497  NaN   NaN        NaN  NaN        NaN   NaN    14.095000  water_temp
74590  NaN   NaN        NaN  NaN        NaN   NaN    13.032000  water_temp
74593  NaN   NaN  78.500000  NaN        NaN   NaN    23.700001  temp-humid
74612  NaN   NaN        NaN  NaN        NaN   NaN    12.657000  water_temp
74626  NaN   NaN        NaN  NaN        NaN   NaN    12.320000  water_temp
74639  NaN   NaN        NaN  NaN        NaN   NaN    12.882000  water_temp
74641  NaN   NaN        NaN  NaN        NaN   NaN    12.695000  water_temp
74686  NaN   NaN  78.599998  NaN        NaN   NaN    20.100000  temp-humid

                    datetime   day  month  place_name        sensor_id    year
71       2019-09-12_12:38:09  12.0    9.0  aquarium_4             None  2019.0
74     2019-09-14_07:30:18_3  14.0    9.0  aquarium_5  28-030897941c59  2019.0
76       2019-09-10_13:55:14  10.0    9.0  aquarium_1             None  2019.0
114      2019-09-12_15:15:29  12.0    9.0  aquarium_5             None  2019.0
151    2019-09-13_03:30:17_1  13.0    9.0  aquarium_1             None  2019.0
217      2019-09-10_11:23:01  10.0    9.0  aquarium_1             None  2019.0
221    2019-09-15_01:00:23_1  15.0    9.0  aquarium_1             None  2019.0
266    2019-09-14_20:30:14_3  14.0    9.0  aquarium_5  28-030897941c59  2019.0
277    2019-09-14_12:30:20_3  14.0    9.0  aquarium_5             None  2019.0
295    2019-09-12_20:30:23_1  12.0    9.0  aquarium_1             None  2019.0
327      2019-09-10_11:29:59  10.0    9.0  aquarium_1  28-030997945f64  2019.0
344    2019-09-13_23:00:18_3  13.0    9.0  aquarium_5             None  2019.0
472    2019-09-13_20:30:25_3  13.0    9.0  aquarium_5              NaN  2019.0
499    2019-09-12_16:30:10_1  12.0    9.0  aquarium_1             None  2019.0
521      2019-09-10_13:05:16  10.0    9.0  aquarium_1  28-030997945f64  2019.0
528    2019-09-13_09:00:16_3  13.0    9.0  aquarium_5              NaN  2019.0
563    2019-09-12_19:30:14_1  12.0    9.0  aquarium_1             None  2019.0
574    2019-09-12_21:00:01_3  12.0    9.0  aquarium_5              NaN  2019.0
576    2019-09-14_00:30:16_1  14.0    9.0  aquarium_1             None  2019.0
615    2019-09-12_22:02:58_1  12.0    9.0  aquarium_1             None  2019.0
657    2019-09-12_23:30:07_1  12.0    9.0  aquarium_1  28-030997945f64  2019.0
679    2019-09-14_07:30:32_3  14.0    9.0  aquarium_5             None  2019.0
733    2019-09-15_05:30:15_3  15.0    9.0  aquarium_5  28-030897941c59  2019.0
788    2019-09-13_00:00:04_3  13.0    9.0  aquarium_5              NaN  2019.0
803    2019-09-14_20:00:17_3  14.0    9.0  aquarium_5  28-030897941c59  2019.0
823      2019-09-12_14:15:30  12.0    9.0  aquarium_5             None  2019.0
887    2019-09-13_21:00:05_3  13.0    9.0  aquarium_5  28-030897941c59  2019.0
953      2019-09-10_14:25:11  10.0    9.0  aquarium_1  28-030997945f64  2019.0
959    2019-09-13_07:00:37_1  13.0    9.0  aquarium_1             None  2019.0
1009   2019-09-13_09:00:09_1  13.0    9.0  aquarium_1  28-030997945f64  2019.0
...                      ...   ...    ...         ...              ...     ...
73448  2019-09-13_12:00:06_3  13.0    9.0  aquarium_5  28-030897941c59  2019.0
73463    2019-09-10_14:17:28  10.0    9.0  aquarium_1             None  2019.0
73498  2019-09-14_00:00:24_1  14.0    9.0  aquarium_1             None  2019.0
73508    2019-09-10_12:40:10  10.0    9.0  aquarium_1  28-030997945f64  2019.0
73638  2019-09-14_16:30:30_3  14.0    9.0  aquarium_5             None  2019.0
73681    2019-09-10_14:46:42  10.0    9.0  aquarium_1  28-030997945f64  2019.0
73709  2019-09-15_08:30:19_3  15.0    9.0  aquarium_5             None  2019.0
73723  2019-09-13_22:00:03_1  13.0    9.0  aquarium_1  28-030997945f64  2019.0
73731    2019-09-10_12:15:19  10.0    9.0  aquarium_1  28-030997945f64  2019.0
73787    2019-09-12_10:56:37  12.0    9.0  aquarium_1  28-030997945f64  2019.0
73803  2019-09-15_04:30:24_3  15.0    9.0  aquarium_5  28-030897941c59  2019.0
73806  2019-09-14_00:00:31_1  14.0    9.0  aquarium_1             None  2019.0
73813  2019-09-12_21:00:02_3  12.0    9.0  aquarium_5  28-030897941c59  2019.0
73937  2019-09-14_03:30:27_3  14.0    9.0  aquarium_5             None  2019.0
73961  2019-09-14_15:00:08_3  14.0    9.0  aquarium_5             None  2019.0
73982  2019-09-13_07:30:01_3  13.0    9.0  aquarium_5  28-030897941c59  2019.0
74077  2019-09-12_19:00:21_3  12.0    9.0  aquarium_5              NaN  2019.0
74280    2019-09-10_12:30:06  10.0    9.0  aquarium_1             None  2019.0
74294  2019-09-13_00:32:57_1  13.0    9.0  aquarium_1             None  2019.0
74300  2019-09-13_14:30:13_3  13.0    9.0  aquarium_5              NaN  2019.0
74312    2019-09-12_14:45:20  12.0    9.0  aquarium_5              NaN  2019.0
74484  2019-09-13_08:30:18_3  13.0    9.0  aquarium_5  28-030897941c59  2019.0
74497  2019-09-12_21:00:13_3  12.0    9.0  aquarium_5  28-030897941c59  2019.0
74590  2019-09-14_22:30:10_3  14.0    9.0  aquarium_5  28-030897941c59  2019.0
74593    2019-09-12_13:45:18  12.0    9.0  aquarium_5              NaN  2019.0
74612  2019-09-14_15:00:22_3  14.0    9.0  aquarium_5  28-030897941c59  2019.0
74626  2019-09-13_00:00:29_1  13.0    9.0  aquarium_1  28-030997945f64  2019.0
74639  2019-09-15_03:00:03_1  15.0    9.0  aquarium_1  28-030997945f64  2019.0
74641  2019-09-15_12:30:11_1  15.0    9.0  aquarium_1  28-030997945f64  2019.0
74686  2019-09-13_19:30:03_3  13.0    9.0  aquarium_5              NaN  2019.0

[2214 rows x 14 columns]